version: '3.4'

services:
  chatdb:
        image: mcr.microsoft.com/mssql/server:2019-latest

  rabbitmq:
        image: rabbitmq:3-management-alpine

  chat.api:
    image: ${DOCKER_REGISTRY-}chatapi
    container_name: chat-api
    build:
      context: .
      dockerfile: Services/Chat.API/Dockerfile

  messagesender.api:
    image: ${DOCKER_REGISTRY-}messagesenderapi
    container_name: chat-api
    build:
      context: .
      dockerfile: Services/MessageSender.API/Dockerfile